# Generated by Django 6.0 on 2025-12-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseexercise',
            name='muscle_group',
            field=models.CharField(choices=[('1', 'CHEST'), ('2', 'BACK'), ('3', 'LEGS'), ('4', 'SHOULDERS'), ('5', 'ARMS'), ('6', 'CORE'), ('7', 'FULLBODY')], default='CHEST', max_length=200),
        ),
    ]
