# Generated by Django 6.0 on 2025-12-09 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_baseexercise_muscle_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseexercise',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.CharField(default='New Workout', max_length=500),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='api.workout'),
        ),
        migrations.AlterField(
            model_name='plannerday',
            name='planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner_days', to='api.planner'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='planner_day',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workout', to='api.plannerday'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL),
        ),
    ]
