# Generated by Django 6.0 on 2025-12-10 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_planner_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='planner_day',
        ),
        migrations.AddField(
            model_name='plannerday',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planner_days', to='api.workout'),
        ),
    ]
