# Generated by Django 6.0 on 2025-12-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_workout_planner_day_plannerday_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseexercise',
            name='video',
            field=models.CharField(default='', max_length=500),
        ),
    ]
